// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VMSAPI.Data;

#nullable disable

namespace VMSAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250202121537_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VMSAPI.Models.Resident", b =>
                {
                    b.Property<int>("RId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IDProofNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IDProofType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("MoveinDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("MoveoutDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<bool>("is_Active")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("RId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("VMSAPI.Models.Society", b =>
                {
                    b.Property<int>("SId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberofBlocks")
                        .HasColumnType("int");

                    b.Property<int>("NumberofUnits")
                        .HasColumnType("int");

                    b.Property<string>("SEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TimeRegistered")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SId");

                    b.ToTable("Societies");
                });
#pragma warning restore 612, 618
        }
    }
}
